//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OC()
        {
            this.OCItens = new HashSet<OCItem>();
        }
    
        public string OC1 { get; set; }
        public string MUNICIPIO { get; set; }
        public string UF { get; set; }
        public Nullable<System.DateTime> DT_INICIO { get; set; }
        public Nullable<System.DateTime> DT_FIM { get; set; }
        public Nullable<int> QTD_ITENS { get; set; }
        public string UNIDADE_COMPRADORA { get; set; }
        public string MODALIDADE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OCItem> OCItens { get; set; }
    }
}
