//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCEncerrada
    {
        public string OC { get; set; }
        public string UNIDADE_COMPRADORA { get; set; }
        public string PROCEDIMENTO { get; set; }
        public string SITUACAO { get; set; }
        public Nullable<System.DateTime> DT_ENCERRAMENTO { get; set; }
    }
}
