//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCItem
    {
        public string OC { get; set; }
        public int NR_SEQUENCIA_ITEM { get; set; }
        public Nullable<int> CD_ITEM { get; set; }
        public Nullable<int> CD_CLASSE_ITEM { get; set; }
        public string DESCRICAO_CLASSE { get; set; }
        public string DESCRICAO_ITEM { get; set; }
        public string UNIDADE_FORNECIMENTO { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
    }
}
