//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemCompra()
        {
            this.ProdutosServicos = new HashSet<ProdutoServico>();
        }
    
        public int codOrdemCompra { get; set; }
        public string descricao { get; set; }
        public string justificativa { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<System.DateTime> dataAprovado { get; set; }
        public Nullable<System.Guid> protocolo { get; set; }
        public Nullable<bool> ativo { get; set; }
        public int codSecretaria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoServico> ProdutosServicos { get; set; }
    }
}
