//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoServico
    {
        public int codProdutoServico { get; set; }
        public Nullable<int> codFornecedor { get; set; }
        public string nome { get; set; }
        public string unidadeMedida { get; set; }
        public Nullable<decimal> precoUnitario { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<bool> ativo { get; set; }
    }
}
