//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampaSoft.Infraestrutura.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampasoftDBEntities : DbContext
    {
        public SampasoftDBEntities()
            : base("name=SampasoftDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fornecedor> Fornecedores { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Orgao> Secretarias { get; set; }
        public virtual DbSet<OCEncerrada> OCEncerradas { get; set; }
        public virtual DbSet<OC> OC { get; set; }
        public virtual DbSet<OCItem> OCItens { get; set; }
        public virtual DbSet<OrdemCompra> OrdensCompras { get; set; }
        public virtual DbSet<ProdutoServico> tbProdutosServicos { get; set; }
        public virtual DbSet<ProdutoServicoFornecedorPreco> tbProdutosServicosFornecedoresPrecos { get; set; }
    }
}
