INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Controladoria Geral do Município','Guilherme Rodrigues Monteiro Mendes','controladoriageral@prefeitura.sp.gov.br','Viaduto do Chá / Ed. Matarazzo','15 / 10° Andar','Centro','(11) 3113-8234 / 156','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria do Governo Municipal','Julio Francisco Semeghini Neto','','Viaduto do Chá / Ed. Matarazzo','15','Centro',' (11) 3113-8000 /156','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Especial de Comunicação','Fábio Souza dos Santos','','Viaduto do Chá / Ed. Matarazzo','15 / 6° Andar','Centro','(11) 3113-8811','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Infraestrutura Urbana e Obras ','Vitor Aly',' siurbimprensa@prefeitura.sp.gov.br','Av. São João','473 / And. 3º,12º ao 19º e 22º','Galeria Olido ','(11) 3337-9900 PABX  ','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Especial de Relações Governamentais','Dr. Milton Flávio','','Viaduto do Chá / Ed. Matarazzo','15 / 10° Andar ','Centro','(11) 3113-8000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal da Pessoa com Deficiência','Cid Torquato Júnior','','Rua: Líbero Badaró','425','32° Andar','(11) 3913-4005','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal da Saúde','Wilson Modesto Pollara','ouvidoriasaude@prefeitura.sp.gov.br','Rua: General Jardim','36','Vila Alburqueque','(11) 3397-2000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Assistência e Desenvolvimento Social','Filipe Tomazelli Sabará','smads@prefeitura.sp.gov.br','Rua: Líbero Badaró','561/569','Centro','(11) 3291-9666 / 9667 ','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal das Prefeituras Regionais','Marcos Penido','','Rua: Líbero Badaró','425','Centro','(11) 31015050','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Cultura',' Andre Luiz Pompeia Sturm','cultura@prefeitura.sp.gov.br','Av. São João','473/  6º ao 10º Andar','Galeria Olido ','(11) 3397-0000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Urbanismo e Licenciamento',' Heloisa Maria de Salles Penteado Proença','imprensasmul@prefeitura.sp.gov.br ','Rua: São Bento','405 / 8°;17°;18°;19°,20°,21°,22°e 23°.','Centro','(11) 3113-7500','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Direitos Humanos e Cidadania','Eloisa Arruda','smdhcgabinete@prefeitura.sp.gov.br','Rua: Liberó Badaró ','119','Centro','(11) 31139601 / 31139602','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Educação','Alexandre Alves Schneider','','Rua: Borges Lagoa ','1230','Vila  Clementino','(11) 3396-0606','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Esportes e Lazer','Jorge Damião de Almeida ','esportessaopaulo@prefeitura.sp.gov.br','Rua: Al. Iraé ','35','Vila Clementino','(11) 33966400','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal da Fazenda','Caio Megale','','Viaduto do Chá / Ed. Matarazzo','15 / 12° Andar','Centro','(11) 3113-8000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Gestão','Paulo Antônio Spencer Uebel','','Viaduto do Chá / Ed. Matarazzo','15','Centro','(11) 31138000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Habitação','Fernando Barrancos Chucre','sehabimprensa@prefeitura.sp.gov.br','Rua: São Bento','405','Centro','(11) 33224500','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Desestatização e Parcerias','Wilson Martins Poit','smdp@prefeitura.sp.gov.br','Rua: Libero Badaró / Ed. Condes Prates','293 / 24° Andar ','Centro','(11) 3113-8000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Relações Internacionais','Julio Serson','smri@prefeitura.sp.gov.br','Viaduto do Chá / Ed. Matarazzo','15 / 7° Andar','Centro','(11) 31138514','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Segurança Urbana','José Roberto Rodrigues de Oliveira','smsuimprensa@prefeitura.sp.gov.br','Rua: Da Consolação','1379','Consolação','(11) 31245100','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Inovação e Tecnologia','Daniel Annenberg','inovacao@prefeitura.sp.gov.br','Rua: Líbero Badaró','425 / 4° , 27° e 34° Andares','Centro','(11) 20757240','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal do Trabalho e Empreendedorismo',' Aline Cardoso','imprensassmte@prefeitura.sp.gov.br','Av. São João','473 / 4° e 5° Andares','Centro','(11) 32246000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal do Verde e do Meio Ambiente','Eduardo de castro','svma@prefeitura.sp.gov.br','Rua Paraíso ','387','Centro','(11) 51870132','08:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Justiça','Rubens Rizek Junior','','Viaduto do Chá / Ed. Matarazzo','15 / 8° Andar','Centro','(11) 31138000','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Secretaria Municipal de Mobilidade e Transportes','João Octaviano Machado Neto','smt@prefeitura.sp.gov.br','Rua: Barão  de Itapetininga','18 / 14° Andar ','Centro','(11) 27963299','09:00','17:00')
INSERT INTO tbSecretarias (nome, nomeSecretario, email, logradouro, numero, bairro, telefone, horaAtendimentoInicial, horaAtendimentoFinal) VALUES ('Procuradoria Geral do Município','Ricardo Ferrari Nogueira','','Viaduto do Chá / Ed. Matarazzo','15 / 10° Andar','Centro','(11) 3113-8614','09:00','17:00')
insert into tbSecretarias (nome, codMunicipio) values ('CONTROLADORIA GERAL DO MUNICIPIO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('GABINETE DO PREFEITO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA DO MUNICÍPIO DE SÃO PAULO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL ARICANDUVA/FORMOSA/CARRAO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL BUTANTA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL CAMPO LIMPO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL CAPELA DO SOCORRO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL CASA VERDE/CACHOEIRINHA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL CIDADE ADEMAR', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL CIDADE TIRADENTES', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL DE SAPOPEMBA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL DE VILA PRUDENTE', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL ERMELINO MATARAZZO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL FREGUESIA/BRASILANDIA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL GUAIANASES', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL IPIRANGA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL ITAIM PAULISTA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL ITAQUERA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL JABAQUARA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL JACANA/TREMEMBE', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL LAPA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL M BOI MIRIM', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL MOOCA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL PARELHEIROS', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL PENHA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL PERUS', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL PINHEIROS', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL PIRITUBA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL SANTANA/TUCURUVI', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL SANTO AMARO', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL SAO MATEUS', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL SAO MIGUEL', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL SE', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL VILA MARIA/VILA GUILHERME', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PREFEITURA REGIONAL VILA MARIANA', 1)
insert into tbSecretarias (nome, codMunicipio) values ('PROCURADORIA GERAL DO MUNICIPIO', 1)

INSERT INTO tbMunicipios VALUES ('São Paulo', 3550308, 'SP')

UPDATE tbSecretarias SET codMunicipio = 1